export enum StatusCode {
    BillNotActive = 'BillNotActive',
    WillNotBeProceededWith = 'WillNotBeProceededWith',
    RoyalAssentAwaiting = 'RoyalAssentAwaiting',
    BillDefeated = 'BillDefeated',
    HouseAtReportStage = 'HouseAtReportStage',
    SenateAtReportStage = 'SenateAtReportStage',
    RoyalAssentGiven = 'RoyalAssentGiven',
    SenateAt1stReading = 'SenateAt1stReading',
    HouseAt1stReading = 'HouseAt1stReading',
    HouseAtReferralToCommitteeBeforeSecondReading = 'HouseAtReferralToCommitteeBeforeSecondReading',
    HouseAt2ndReading = 'HouseAt2ndReading',
    HouseAtReportStageAndSecondReading = 'HouseAtReportStageAndSecondReading',
    SenateAt2ndReading = 'SenateAt2ndReading',
    SenateAt3rdReading = 'SenateAt3rdReading',
    HouseAt3rdReading = 'HouseAt3rdReading',
    HouseInCommittee = 'HouseInCommittee',
    SenateInCommittee = 'SenateInCommittee',
    SenateConsiderationOfCommitteeReport = 'SenateConsiderationOfCommitteeReport',
    HouseConsiderationOfCommitteeReport = 'HouseConsiderationOfCommitteeReport',
    SenateConsiderationOfAmendments = 'SenateConsiderationOfAmendments',
    HouseConsiderationOfAmendments = 'HouseConsiderationOfAmendments',
    Introduced = 'Introduced',
    ProForma = 'ProForma',
    SenateBillWaitingHouse = 'SenateBillWaitingHouse',
    HouseBillWaitingSenate = 'HouseBillWaitingSenate',
    OutsideOrderPrecedence = 'OutsideOrderPrecedence',
    SenConsideringHouseAmendments = 'SenConsideringHouseAmendments',
    HouseConsideringSenAmendments = 'HouseConsideringSenAmendments',
}

export const STATUS_CODES: Record<StatusCode, string> = {
    [StatusCode.BillNotActive]: 'Not active',
    [StatusCode.WillNotBeProceededWith]: 'Dead',
    [StatusCode.RoyalAssentAwaiting]: 'Awaiting royal assent',
    [StatusCode.BillDefeated]: 'Defeated',
    [StatusCode.HouseAtReportStage]: 'Report stage (House)',
    [StatusCode.SenateAtReportStage]: 'Report stage (Senate)',
    [StatusCode.RoyalAssentGiven]: 'Law (royal assent given)',
    [StatusCode.SenateAt1stReading]: 'First reading (Senate)',
    [StatusCode.HouseAt1stReading]: 'First reading (House)',
    [StatusCode.HouseAtReferralToCommitteeBeforeSecondReading]: 'Referral to committee before 2nd reading (House)',
    [StatusCode.HouseAt2ndReading]: 'Second reading (House)',
    [StatusCode.HouseAtReportStageAndSecondReading]: 'Report stage and second reading (House)',
    [StatusCode.SenateAt2ndReading]: 'Second reading (Senate)',
    [StatusCode.SenateAt3rdReading]: 'Third reading (Senate)',
    [StatusCode.HouseAt3rdReading]: 'Third reading (House)',
    [StatusCode.HouseInCommittee]: 'In committee (House)',
    [StatusCode.SenateInCommittee]: 'In committee (Senate)',
    [StatusCode.SenateConsiderationOfCommitteeReport]: 'Considering committee report (Senate)',
    [StatusCode.HouseConsiderationOfCommitteeReport]: 'Considering committee report (House)',
    [StatusCode.SenateConsiderationOfAmendments]: 'Considering amendments (Senate)',
    [StatusCode.HouseConsiderationOfAmendments]: 'Considering amendments (House)',
    [StatusCode.Introduced]: 'Introduced',
    [StatusCode.ProForma]: 'Not a real bill (bills C-1 and S-1 are weird procedural relics)',
    [StatusCode.SenateBillWaitingHouse]: 'Senate bill, now waiting to be considered in the House',
    [StatusCode.HouseBillWaitingSenate]: 'Bill passed the House, now waiting to be considered in the Senate',
    [StatusCode.OutsideOrderPrecedence]: "Outside the Order of Precedence (a private member's bill that hasn't yet won the draw that determines which private member's bills can be debated)",
    [StatusCode.SenConsideringHouseAmendments]: 'At consideration in the Senate of amendments made by the House of Commons',
    [StatusCode.HouseConsideringSenAmendments]: 'At consideration in the House of Commons of amendments made by the Senate',
}